### ISSUE TITLE
正确解析JSON

### ISSUE THREAD

**Issue by MackDing** [ran123123123/hande#4]
在你的代码中，const.EV_AUTO_TEST_CONFIG_PARAMS是一个JSON字符串，但它使用了单引号而不是双引号。你需要将所有的单引号替换为双引号才能正确解析JSON。

  config = json.loads(const.EV_AUTO_TEST_CONFIG_PARAMS.replace("'", "\""))

**Comment by ran123123123** [comment]
> 在你的代码中，const.EV_AUTO_TEST_CONFIG_PARAMS是一个JSON字符串，但它使用了单引号而不是双引号。你需要将所有的单引号替换为双引号才能正确解析JSON。
> 
> config = json.loads(const.EV_AUTO_TEST_CONFIG_PARAMS.replace("'", """))

good

**Comment by MackDing** [comment]
reopen ?
